apiVersion: apps/v1
kind: Deployment
metadata:
  name: conference
  labels:
    app: conference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conference
  template:
    metadata:
      labels:
        app: conference
    spec:
      containers:
        - name: conference
          image: meetingroomacr.azurecr.io/conference:latest
          ports:
            - containerPort: 8080
          env:
            - name: RESERVE
              valueFrom:
                configMapKeyRef:
                  name: apiurl
                  key: reserveapiurl
            - name: ROOM
              valueFrom:
                configMapKeyRef:
                  name: apiurl
                  key: roomapiurl